version: '3.8'

services:

  # FastAPI
  web:
    image: web-app
    container_name: web-service
    hostname: web.service
    restart: on-failure
    build:
      context: ../
    command: "gunicorn manage:backend --worker-class uvicorn.workers.UvicornWorker --workers 1 --worker-connections=50 --timeout=30 --keep-alive=60 --bind=0.0.0.0:8000"
    env_file: .env
    environment:
      SPATIALITE_PATH: /usr/lib/mod_spatialite.so.7
    volumes:
      - ../sql.db:/address_book/sql.db
    ports:
        - "8000:8000"